dict = {
    1: {"name": "THE LOVERS", "key": " union, love, harmony, relationships, joy", "reversed": " self-love, disharmony, imbalance"},
    2: {"name": "FIVE of PENTACLES", "key": " loss, isolation, poverty, worry, illness", "reversed": " recovery, forgiveness, welcome"},
    3: {"name": "TEMPERANCE", "key": " balance, moderation, patience, healing", "reversed": " Imbalance, excess, self-healing"},
    4: {"name": "THE EMPEROR", "key": " authority, fatherhood, structure, protection", "reversed": " tyranny, rigidity, coldness"},
    5: {"name": "THE EMPRESS", "key": " creation, kindness, nature, motherhood", "reversed": " unfulfilled, dependence, smothered, devouring"},
    6: {"name": "TEN of PENTACLES", "key": " wealth, contribution, abundance, family", "reversed": " financial failure, discord, broken home"},
    7: {"name": "THE SUN", "key": " happiness, success, vitality, knowledge", "reversed": " depression, negativity, uncreative"},
    8: {"name": "QUEEN of PENTACLES", "key": " practicality, providing, loving, security", "reversed": " self-care, work-life balance, contemplative"},
    9: {"name": "THREE of SWORDS", "key": " heartbreak, betrayal, emotional pain, grief", "reversed": " healing, forgiveness, moving on, negative self-talk"},
    10: {"name": "ACE of SWORDS", "key": " clarity, breakthrough, truth, success", "reversed": " re-thinking, confusion, chaos, mental block"},
    11: {"name": "FOUR of PENTACLES", "key": " hoarding, possessiveness, greed, security", "reversed": " generosity, sharing, protection"},
    12: {"name": "PAGE of PENTACLES", "key": " learning, scholarship, apprenticeship, manifestation", "reversed": " lack of progress, laziness, learning from failure"},
    13: {"name": "TWO of PENTACLES", "key": " balance, adaptability, time management, priorities", "reversed": " imbalance, disorganization, overwhelm"},
    14: {"name": "SEVEN of SWORDS", "key": " secrecy, strategy, getting away with it, self-interest", "reversed": " imposter syndrome, keeping secrets, self deceit"},
    15: {"name": "ACE of WANDS", "key": " expansion, inspiration, creation, new beginnings", "reversed": " lack of inspiration, delays, false starts"},
    16: {"name": "ACE of PENTACLES", "key": " wealth, new opportunities, manifestation, abundance", "reversed": " missed opportunity, lack of resources, generosity"},
    17: {"name": "THE HANGED MAN", "key": " surrender, suspension, letting go, enlightenment", "reversed": " stuck, indecision, resistance to change"},
    18: {"name": "THE HERMIT", "key": " introspection, solitude, guidance, meditation", "reversed": " isolation, loneliness, withdrawal"},
    19: {"name": "FIVE of CUPS", "key": " loss, regret, disappointment, grief", "reversed": " acceptance, moving on, finding peace"},
    20: {"name": "EIGHT of PENTACLES", "key": " skill development, hard work, apprenticeship, mastery", "reversed": " perfectionism, no growth, repetition"},
    21: {"name": "KNIGHT of PENTACLES", "key": " hard work, responsibility, routine, loyalty", "reversed": " laziness, feeling stuck, boredom"},
    22: {"name": "TWO of WANDS", "key": " planning, progress, direction, determination", "reversed": " fear of unknown, lack of planning, impulsive decisions"},
    23: {"name": "STRENGTH", "key": " inner strength, courage, compassion, maturity", "reversed": " self-doubt, weakness, insecurity"},
    24: {"name": "FOUR of SWORDS", "key": " stillness, rest, contemplation, restoration", "reversed": " restlessness, burnout, stress"},
    25: {"name": "PAGE of CUPS", "key": " emotional exploration, creativity, intuition, curiosity", "reversed": " new ideas, emotional immaturity, creative block, lack of intuition"},
    26: {"name": "KNIGHT of CUPS", "key": " romantic, imaginative, intuitive, artistic, charm", "reversed": " jealousy, moodiness, unrealistic, creative block"},
    27: {"name": "TWO of SWORDS", "key": " blocked vision, difficult choices, indecision, avoidance, options", "reversed": " indecision, confusion, information overload"},
    28: {"name": "TEN of SWORDS", "key": " painful ending, betrayal, crisis, rock bottom, melodrama", "reversed": " recovery, regeneration, resisting an inevitable end"},
    29: {"name": "ACE of CUPS", "key": " new emotional beginnings, intuition, creativity", "reversed": " emotional blockages, lack of creativity, missed opportunity"},
    30: {"name": "QUEEN of SWORDS", "key": " clarity, independence, logic, communication, perceptive", "reversed": " cruelty, bitterness, coldness"},
    31: {"name": "PAGE of WANDS", "key": " inspiration, exploration, free spirit, passion", "reversed": " new ideas, lack of direction, creative block, impulsive behavior"},
    32: {"name": "SIX of SWORDS", "key": " transition, leaving behind, moving on, travel, hope", "reversed": " emotional baggage, unresolved issues, resisting change"},
    33: {"name": "FOUR of WANDS", "key": " completion, celebration, harmony, homecoming", "reversed": " domestic disputes, disunity, instability"},
    34: {"name": "SIX of PENTACLES", "key": " generosity, charity, sharing wealth, growth", "reversed": " selfishness, debt, inequitable"},
    35: {"name": "THREE of WANDS", "key": " the future, foresight, opportunity", "reversed": " lack of foresight, delays, obstacles"},
    36: {"name": "EIGHT of WANDS", "key": " movement, progress, action, liminal", "reversed": " delays, frustration, miscommunication"},
    37: {"name": "NINE of SWORDS", "key": " anxiety, fear, nightmares, anguish", "reversed": " inner turmoil, release, facing fears, secrets"},
    38: {"name": "EIGHT of CUPS", "key": " moving on, stagnation, letting go", "reversed": " walking away, fear of change, indecision, escapism"},
    39: {"name": "NINE of CUPS", "key": " fulfillment, satisfaction, gratitude, bliss", "reversed": " indulgence, complacency, greed, materialism"},
    40: {"name": "THE FOOL", "key": " innocence, new beginnings, impulsiveness, free spirit", "reversed": " recklessness, foolishness, naivety, running away"},
    41: {"name": "THE DEVIL", "key": " addiction, materialism, bondage, negativity", "reversed": " breaking free, detachment, overcoming"},
    42: {"name": "THE TOWER", "key": " sudden change, upheaval, chaos", "reversed": " personal transformation, fear of change, averting disaster"},
    43: {"name": "PAGE of SWORDS", "key": " ambitious, curious, restless, honest, thirst for knowledge", "reversed": " easily distracted, reckless, rash, self-expression"},
    44: {"name": "THE MAGICIAN", "key": " manifestation, resourcefulness, power, action", "reversed": " manipulation, poor planning, untapped talents"},
    45: {"name": "SEVEN of PENTACLES", "key": " patience, perseverance, hard work, contemplation", "reversed": " work without results, impatience, giving up too soon"},
    46: {"name": "TEN of CUPS", "key": " divine love, blissful relationships, harmony, alignment, radiating energy", "reversed": " disconnection, misaligned values, struggling relationships"},
    47: {"name": "EIGHT of SWORDS", "key": " trapped, powerless, self-imposed restrictions, negative thoughts", "reversed": " self-acceptance, new perspectives, breaking free, inner critic"},
    48: {"name": "TWO of CUPS", "key": " partnership, unity, connection, love", "reversed": " imbalance, broken relationships, disconnection"},
    49: {"name": "KNIGHT of SWORDS", "key": " ambitious, action-oriented, driven, forceful", "reversed": " impatient, impulsive, overbearing, burn-out"},
    50: {"name": "KING of SWORDS", "key": " authority, intellectual power, truth, fair", "reversed": " manipulation, abusive, cold-hearted, misuse of power"},
    51: {"name": "FIVE of SWORDS", "key": " conflict, betrayal, defeat", "reversed": " forgive, making amends, past resentment"},
    52: {"name": "KING of CUPS", "key": " compassion, diplomacy, control of emotions, mentorship", "reversed": " manipulative, self-compassion, untrustworthy"},
    53: {"name": "FIVE of WANDS", "key": " scattered, competition, disagreement, tension", "reversed": " avoiding conflict, teamwork, finding common ground"},
    54: {"name": "SEVEN of WANDS", "key": " inner strength, defensive, perseverance, courage", "reversed": " giving up, overwhelm, losing control"},
    55: {"name": "NINE of PENTACLES", "key": " luxury, financial independence, self-sufficiency, peace", "reversed": " over-investment, unfulfilled, codependency, lack of resources"},
    56: {"name": "THE MOON", "key": " deception, confusion, the unconscious, dreams", "reversed": " release of fear, illusion, facing the unknown"},
    57: {"name": "KNIGHT of WANDS", "key": " passion, adventure, fearlessness, adventurous", "reversed": " recklessness, impulsiveness, lack of direction"},
    58: {"name": "SIX of WANDS", "key": " victory, public recognition, progress", "reversed": " ego, self-doubt, lack of recognition"},
    59: {"name": "SEVEN of CUPS", "key": " opportunities, decision-making, confusion, illusion", "reversed": " clarity, realistic expectations, groundedness, deception"},
    60: {"name": "THE HIGH PRIESTESS", "key": " intuition, mystery, inner wisdom", "reversed": " disconnected, emotional insecurity, ignoring intuition"},
    61: {"name": "KING of PENTACLES", "key": " dicipline, leadership, security, control", "reversed": " greed, materialism, stubborn, reckless spending"},
    62: {"name": "THE CHARIOT", "key": " triumph, willpower, self-control", "reversed": " lack of control, aggression, self-doubt"},
    63: {"name": "THE STAR", "key": " hope, inspiration, serenity", "reversed": " disillusionment, lack of faith, despair"},
    64: {"name": "TEN of WANDS", "key": " burden, responsibility, hard work, difficulty", "reversed": " inability to delegate, overstressed, burnt out"},
    65: {"name": "THREE of PENTACLES", "key": " teamwork, collaboration, planning, learning", "reversed": " lack of teamwork, miscommunication, working alone"},
    66: {"name": "THREE of CUPS", "key": " celebration, friendship, creativity, bounty", "reversed": " overindulgence, excess, dissipation"},
    67: {"name": "QUEEN of CUPS", "key": " compassion, emotional stability, intuition, insight", "reversed": " martyrdom, emotional insecurity, self care"},
    68: {"name": "WHEEL of FORTUNE", "key": " change, cycles, inevitability, destiny", "reversed": " no control, bad luck, unwelcome changes"},
    69: {"name": "DEATH", "key": " change, transformation, endings, beginnings", "reversed": " fear of change, stagnation, holding on"},
    70: {"name": "FOUR of CUPS", "key": " apathy, contemplation, re-evaluation", "reversed": " boredom, greed, seeking more, looking inward"},
    71: {"name": "SIX of CUPS", "key": " nostalgia, memories, innocence, kindness", "reversed": " moving forward, forgiveness, leaving behind"},
    72: {"name": "THE WORLD", "key": " completion, fulfillment, wholeness", "reversed": " incomplete, lack of closure, stagnation"},
    73: {"name": "KING of WANDS", "key": " big picture, leader, boldness, vision", "reversed": " impulsiveness, haste, ruthlessness"},
    74: {"name": "THE HIEROPHANT", "key": " tradition, conformity, spiritual guidance, mentor", "reversed": " rebellion, challenging the status quo, nonconformity"},
    75: {"name": "QUEEN of WANDS", "key": " courage, determination, independence", "reversed": " selfishness, jealousy, insecurities"},
    76: {"name": "NINE of WANDS", "key": " resilience, grit, persistence, boundaries", "reversed": " burnt out, overwhelmed, giving up, paranoia"},
    77: {"name": "JUSTICE", "key": " fairness, truth, balance, karma", "reversed": " injustice, dishonesty, imbalance"},
    78: {"name": "JUDGEMENT", "key": " rebirth, awakening, absolution, forgiveness", "reversed": " denial, self-doubt, refusal to change"}
}